spring:
  application:
    name: MultiPIM

  datasource:
    url: jdbc:mysql://localhost:33306/multi-tenant-db?useSSL=false&serverTimezone=UTC
    username: multi-tenant-user
    password: multi-tenant-password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000

  data:
    redis:
      host: localhost
      port: 6379
      password: redis-multi-tenant-password

server:
  port: 8972
#  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  sign-key: "tenant-jwt-secret-sdflsensdgjsklafjklsjefisl"
